### ISSUE TITLE
Meeting:

### ISSUE THREAD

**Issue by trainfarb** [deg-entreprises/A.2.7-Investor-Platform#7]
# DEG Entreprises - AGENDA
## Draft DEG's Research Proposal for its A.2.7 Investor Platform
Date: 2024.03.03.SUN
Location: Virtual

### PURPOSE
`A.2.7 Investor Platform: What is the purpose of this meeting?`
The purpose of this meeting is to develop and publish a research proposal for DEG's A.2.7 Investor Platform.

### PARTICIPANTS
`B.0.9 Onboarding Platform: Who is contributing to this meeting?`
- OWNER: 
  - DEG Entreprises
  - Make Light of It
- PRODUCER: 
  - trainfarb: am I wrong?
- PROVIDER: 
  - hu3agency: we're all right
- CONSUMER: 
  - ourStory: Everything Is Music

### AGENDA
`B.9.0 Training Platform: What is the agenda for this meeting?`
1. Review Existing Website based on DEG comments and capture Felix’s Feedback
2. Explain risks of me working behind closed doors and presenting website
3. Explain the need for a clearer timeline for DEG to understand how Go-To-Market Strategy works
4. Present Recommended Landing Page based on P3 Template and explain benefits to not changing the structure
5. Explain that all suggestions from DEG can fit into the P3 Website Template with Relume presentation
6. Highlight Schedule
  - February = Investor Platform; Meeting Protocol and Default Platform Landing Page Structure
    - Show FigJam
    - Meeting Protocol
    - Draft Management and Design Protocol
    - Draft Marketing and Sales Protocol
    - Draft Communications and Story Protocol
    - Will be sending a recap of the month to DEG on March 7th
    - Will be formalizing all meeting notes from 2023 trip on March 8th and 9th
  - March = Onboarding Platform and beginning Documentation for Supply Chain Meetings
  - April = Training Platform to create first iteration of capacity building for suppliers, manufacturers, and the market
  - May = Governance Platform to define go-to-market strategy
  - June = Management Platform to show how decentralized tasks are managed
  - July = Design Platform to finalize the branding for DEG
    - Highlight task list for website to track all suggestions (GitHub Projects)
  - August = Marketing Platform to implement ecosystem marketing strategy
  - September = Sales Platform to optimize website and sales strategy for growing network
  - October = Communications Platform to grow newsletter and empower Alcoholic Beverage Manufacturers to define how platform will evolve
  - November, December, January = Story platform to develop annual report and DEG’s annual platform investor relations summit

### GOAL
`C.1.8 Governance Platform: What is the longterm goal of this meeting?`
Gain alignment on how future DEG platforms will begin.

### MILESTONES
`D.8.1 Management Platform: What milestone(s) is/are associated with this meeting?`
- [x] OWNER/ Fundraising: Close Investment Round
- [ ] PRODUCER/ Supply Chain: Store First Batch of Dried Malanga
- [ ] PROVIDER/ Manufacturing: Break Ground for Manufacturing Facility
- [ ] CONSUMER/ Market: Host First Malanga ENA Conference

### ATTACHMENTS
`E.7.2 Design Platform: What attachments supports this meeting?`
- OWNER/ Biomimicry:
  - 
- PRODUCER/ Machine Learning:
  - 
- PROVIDER/ Civil Engineering:
  - 
- CONSUMER/ Blockchain:
  - [Rwanda Vision 2050](https://drive.google.com/file/d/1l2Yh1G1pkvbuRp_UArKnnCGkudSFaYtg/view?usp=sharing)
  - 

### RISKS
`F.6.3 Marketing Platform: What risk(s) is/are addressed with this meeting?`
- If we don't use a predetermined website structure, then we will spend more time on web design where more benefit would be derived from implementing the go-to-market strategy.
- If we don't have a clear schedule with buy-in from all parties, then communication will suffer and we'll delay progress of go-to-market strategy implementation

### CASE STUDY
`G.5.4 Sales Platform: How will you describe the value proposition of this meeting?`
- Situation: Need to finalize the initial website.
- Complication: Additional input that deviates from the P3 Template Landing page added complexity.
- Resolution: Agree on the longterm schedule and develop a protocol for capturing and organizing suggestions that can be implemented at the appropriate time in the go-to-market strategy schedule.

**Comment by trainfarb** [comment]
- 2024.03.05: Summarize meeting and send to Felix & Karl
- 2024.03.06: Incorporate existing website design into P3 Template structure and send to DEG
- 2024.03.07: Send presentation of February progress
- 2024.03.09: Send 2023 Meeting Summary

Q: How will designs fit in? July

Administration Suggestion from Felix: Can we get contract office professionals in Rwanda to teach them meeting notes so they can capture these? Then they report to me and remove the burden. 
- This aligns perfectly with March focus with Onboarding Documentation
- Ex. had great process at DOW, but they couldn't be implemented optimally bc of other requirements. We want to avoid that.
- Goal: start with people on a contract basis. Onboarding executive assistants who know the meeting protocol so they become part of the platform. Executive Assistants use the AI assistant to capture and translate notes.
- How can we strip away the complexity?
- Focus on prompt engineering for them
- This is the case study that we use for March
- Clear focus for March. Show value of decentralized platform. I'm able to support remote.
- Questions:
  - What's the best tool?
  - Ipad? Chrome Book? Remarkable?
  - Provide suggestion as an onboarding tool
- Benefit of scribe helping us growing out the story
- This onboarding strategy to really tie into how the platform evolves across Africa

Question: What are the challenges with finding someone to help with coding?
* Creating a budget so we can create template that others can build out

Karl asked BDO about risk mitigation for supply chain. They're projecting funding by August. They want to ensure we have a clear path to revenue, manufacting, and supply chain.

Friday - Risk mitigation strategy to BK and BDO. Remove risk for funding by August 2024

First two weeks to engage with Rwanda Development bank with Maggie. 

Tomorrow we should know about MINICOM land
Beginning of trip know more about wetland
Supply Chain RAB Agreement almost complete
Already have the 3 LOIs
Present this to Rwanda Development Bank so they can see how our processes can align. Having them onboard would help drive more investors to add pressure to BK Capital and RAB.

May - Projected India trip to understand the supply chain so we know importers business even better.
